name: Reusable workflow Demo
on:
    workflow_call:
        inputs:
            who-to-greet:
                description: 'The person to greet'
                default: 'World'
                required: true
                type: string

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"